"""实体张量合同常量。"""

ENTITY_COUNT = 16
ENTITY_KINEMATIC_DIM = 4
ENTITY_EMBEDDING_DIM = 64
ENTITY_FEATURE_DIM = ENTITY_KINEMATIC_DIM + ENTITY_EMBEDDING_DIM
ENTITY_GEOMETRY_DIM = ENTITY_FEATURE_DIM

POSITION_SCALE_M = 20.0
VELOCITY_SCALE_MPS = 5.0
